### ISSUE TITLE
Events with custom recurrence return the end of the first time in last_event_end()

### ISSUE THREAD

**Issue by zrothauser** [cmoa/wp-museum-calendar#3]
**Issue:**
For an event with custom dates set for the "Recurrence" setting, the `CMOA_Event::last_event_end()` method will return the end time of the _first_ event in the series of recurrences, rather than the last.

<img width="966" alt="captura de tela 2018-04-15 11 38 17" src="https://user-images.githubusercontent.com/4950114/38780803-ca06d736-40a1-11e8-90db-485a9265509a.png">

<img width="603" alt="captura de tela 2018-04-15 11 40 52" src="https://user-images.githubusercontent.com/4950114/38780812-e234fbf8-40a1-11e8-85db-9c01d3889e0f.png">

**Expected behavior:** 
The end time of the last date in the series should be returned.

**Comment by pburke** [comment]
Closed by #4.
